// Generated by scripts/scraping-local/update_models.py
// Source: https://openrouter.ai/models?max_price=0
// Generated at: 2026-04-19T13:06:33+00:00

export const models = [
  {
    "model_name": "Arcee AI: Trinity Large Preview (free)",
    "model_id": "arcee-ai/trinity-large-preview:free",
    "context": 131000,
    "input_cost_per_m": 0.0,
    "output_cost_per_m": 0.0,
    "released_date": "2026-01-27"
  },
  {
    "model_name": "Elephant",
    "model_id": "openrouter/elephant-alpha",
    "context": 262144,
    "input_cost_per_m": 0.0,
    "output_cost_per_m": 0.0,
    "released_date": "2026-04-13"
  },
  {
    "model_name": "Free Models Router",
    "model_id": "openrouter/free",
    "context": 200000,
    "input_cost_per_m": 0.0,
    "output_cost_per_m": 0.0,
    "released_date": "2026-02-01"
  },
  {
    "model_name": "Google: Gemma 3 12B (free)",
    "model_id": "google/gemma-3-12b-it:free",
    "context": 32768,
    "input_cost_per_m": 0.0,
    "output_cost_per_m": 0.0,
    "released_date": "2025-03-13"
  },
  {
    "model_name": "Google: Gemma 3 27B (free)",
    "model_id": "google/gemma-3-27b-it:free",
    "context": 131072,
    "input_cost_per_m": 0.0,
    "output_cost_per_m": 0.0,
    "released_date": "2025-03-12"
  },
  {
    "model_name": "Google: Gemma 3 4B (free)",
    "model_id": "google/gemma-3-4b-it:free",
    "context": 32768,
    "input_cost_per_m": 0.0,
    "output_cost_per_m": 0.0,
    "released_date": "2025-03-13"
  },
  {
    "model_name": "Google: Gemma 3n 2B (free)",
    "model_id": "google/gemma-3n-e2b-it:free",
    "context": 8192,
    "input_cost_per_m": 0.0,
    "output_cost_per_m": 0.0,
    "released_date": "2025-07-09"
  },
  {
    "model_name": "Google: Gemma 3n 4B (free)",
    "model_id": "google/gemma-3n-e4b-it:free",
    "context": 8192,
    "input_cost_per_m": 0.0,
    "output_cost_per_m": 0.0,
    "released_date": "2025-05-20"
  },
  {
    "model_name": "Google: Gemma 4 26B A4B  (free)",
    "model_id": "google/gemma-4-26b-a4b-it:free",
    "context": 262144,
    "input_cost_per_m": 0.0,
    "output_cost_per_m": 0.0,
    "released_date": "2026-04-03"
  },
  {
    "model_name": "Google: Gemma 4 31B (free)",
    "model_id": "google/gemma-4-31b-it:free",
    "context": 262144,
    "input_cost_per_m": 0.0,
    "output_cost_per_m": 0.0,
    "released_date": "2026-04-02"
  },
  {
    "model_name": "Google: Lyria 3 Clip Preview",
    "model_id": "google/lyria-3-clip-preview",
    "context": 1048576,
    "input_cost_per_m": 0.0,
    "output_cost_per_m": 0.0,
    "released_date": "2026-03-30"
  },
  {
    "model_name": "Google: Lyria 3 Pro Preview",
    "model_id": "google/lyria-3-pro-preview",
    "context": 1048576,
    "input_cost_per_m": 0.0,
    "output_cost_per_m": 0.0,
    "released_date": "2026-03-30"
  },
  {
    "model_name": "LiquidAI: LFM2.5-1.2B-Instruct (free)",
    "model_id": "liquid/lfm-2.5-1.2b-instruct:free",
    "context": 32768,
    "input_cost_per_m": 0.0,
    "output_cost_per_m": 0.0,
    "released_date": "2026-01-20"
  },
  {
    "model_name": "LiquidAI: LFM2.5-1.2B-Thinking (free)",
    "model_id": "liquid/lfm-2.5-1.2b-thinking:free",
    "context": 32768,
    "input_cost_per_m": 0.0,
    "output_cost_per_m": 0.0,
    "released_date": "2026-01-20"
  },
  {
    "model_name": "Meta: Llama 3.2 3B Instruct (free)",
    "model_id": "meta-llama/llama-3.2-3b-instruct:free",
    "context": 131072,
    "input_cost_per_m": 0.0,
    "output_cost_per_m": 0.0,
    "released_date": "2024-09-25"
  },
  {
    "model_name": "Meta: Llama 3.3 70B Instruct (free)",
    "model_id": "meta-llama/llama-3.3-70b-instruct:free",
    "context": 65536,
    "input_cost_per_m": 0.0,
    "output_cost_per_m": 0.0,
    "released_date": "2024-12-06"
  },
  {
    "model_name": "MiniMax: MiniMax M2.5 (free)",
    "model_id": "minimax/minimax-m2.5:free",
    "context": 196608,
    "input_cost_per_m": 0.0,
    "output_cost_per_m": 0.0,
    "released_date": "2026-02-12"
  },
  {
    "model_name": "Nous: Hermes 3 405B Instruct (free)",
    "model_id": "nousresearch/hermes-3-llama-3.1-405b:free",
    "context": 131072,
    "input_cost_per_m": 0.0,
    "output_cost_per_m": 0.0,
    "released_date": "2024-08-16"
  },
  {
    "model_name": "NVIDIA: Nemotron 3 Nano 30B A3B (free)",
    "model_id": "nvidia/nemotron-3-nano-30b-a3b:free",
    "context": 256000,
    "input_cost_per_m": 0.0,
    "output_cost_per_m": 0.0,
    "released_date": "2025-12-14"
  },
  {
    "model_name": "NVIDIA: Nemotron 3 Super (free)",
    "model_id": "nvidia/nemotron-3-super-120b-a12b:free",
    "context": 262144,
    "input_cost_per_m": 0.0,
    "output_cost_per_m": 0.0,
    "released_date": "2026-03-11"
  },
  {
    "model_name": "NVIDIA: Nemotron Nano 12B 2 VL (free)",
    "model_id": "nvidia/nemotron-nano-12b-v2-vl:free",
    "context": 128000,
    "input_cost_per_m": 0.0,
    "output_cost_per_m": 0.0,
    "released_date": "2025-10-28"
  },
  {
    "model_name": "NVIDIA: Nemotron Nano 9B V2 (free)",
    "model_id": "nvidia/nemotron-nano-9b-v2:free",
    "context": 128000,
    "input_cost_per_m": 0.0,
    "output_cost_per_m": 0.0,
    "released_date": "2025-09-05"
  },
  {
    "model_name": "OpenAI: gpt-oss-120b (free)",
    "model_id": "openai/gpt-oss-120b:free",
    "context": 131072,
    "input_cost_per_m": 0.0,
    "output_cost_per_m": 0.0,
    "released_date": "2025-08-05"
  },
  {
    "model_name": "OpenAI: gpt-oss-20b (free)",
    "model_id": "openai/gpt-oss-20b:free",
    "context": 131072,
    "input_cost_per_m": 0.0,
    "output_cost_per_m": 0.0,
    "released_date": "2025-08-05"
  },
  {
    "model_name": "Qwen: Qwen3 Coder 480B A35B (free)",
    "model_id": "qwen/qwen3-coder:free",
    "context": 262000,
    "input_cost_per_m": 0.0,
    "output_cost_per_m": 0.0,
    "released_date": "2025-07-23"
  },
  {
    "model_name": "Qwen: Qwen3 Next 80B A3B Instruct (free)",
    "model_id": "qwen/qwen3-next-80b-a3b-instruct:free",
    "context": 262144,
    "input_cost_per_m": 0.0,
    "output_cost_per_m": 0.0,
    "released_date": "2025-09-11"
  },
  {
    "model_name": "Venice: Uncensored (free)",
    "model_id": "cognitivecomputations/dolphin-mistral-24b-venice-edition:free",
    "context": 32768,
    "input_cost_per_m": 0.0,
    "output_cost_per_m": 0.0,
    "released_date": "2025-07-09"
  },
  {
    "model_name": "Z.ai: GLM 4.5 Air (free)",
    "model_id": "z-ai/glm-4.5-air:free",
    "context": 131072,
    "input_cost_per_m": 0.0,
    "output_cost_per_m": 0.0,
    "released_date": "2025-07-25"
  }
];

export default models;
